name: 2020_scheibler_overiva
dependencies:
  - python=3.7
  - numpy
  - scipy>=0.18.0
  - mkl-service
  - matplotlib
  - pandas
  - ipyparallel
  - pip
  - pip:
    - seaborn==0.9.0
    - gitpython
    - pyroomacoustics==0.3.1
    - sounddevice
    - samplerate
    - mir_eval
    - sounddevice
    - colorspacious
